apiVersion: v1
kind: Service
metadata:
  name: {{ include "mumbleserver.fullname" . }}
  labels:
    {{- include "mumbleserver.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ required "A valid .Values.mumble.server_domain entry required!" .Values.mumble.server_domain }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if and (not .Values.use_certmanager) (not .Values.mumble.disable_tls) }}
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
    - port: 64738
      targetPort: mumble-tcp
      protocol: TCP
      name: mumble-tcp
    - port: 64738
      targetPort: mumble-udp
      protocol: UDP
      name: mumble-udp
  selector:
    {{- include "mumbleserver.selectorLabels" . | nindent 4 }}
